[package]
name = "just-jimage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
thiserror = "1"

[dev-dependencies]
log = "0.4"
memmap = "0.7"
pretty_env_logger = "0.4"
